from importlib.metadata import PackageNotFoundError, version

from .entity_manager import AsyncEntityManager
from .exceptions import PersistenceError, SkrySqlaError
from .filters import (
    And,
    ArrayContains,
    ArrayOverlap,
    Between,
    Contains,
    EndsWith,
    Equal,
    Filter,
    GreaterOrEqual,
    GreaterThan,
    ILike,
    In,
    IsNotNull,
    IsNull,
    JsonContains,
    JsonHasKey,
    LessOrEqual,
    LessThan,
    Like,
    Not,
    NotEqual,
    NotIn,
    Or,
    StartsWith,
)
from .model import (
    M_ID,
    M_TS,
    M_UID,
    Base,
    CreatedAtMixin,
    CreatedUpdatedAtMixin,
    IDMixin,
    M,
    TimestamableMixin,
    TimestampableMixin,
    UpdatedAtMixin,
    UUIDIDMixin,
)
from .repository import AsyncRepository, QueryBuilder, SelectOptions, apply_options

try:
    __version__ = version("skry-sqla")
except PackageNotFoundError:
    __version__ = "0.1.0"

__all__ = [
    "__version__",
    "AsyncEntityManager",
    "AsyncRepository",
    "QueryBuilder",
    "SelectOptions",
    "Base",
    "CreatedAtMixin",
    "CreatedUpdatedAtMixin",
    "IDMixin",
    "M",
    "M_ID",
    "M_UID",
    "M_TS",
    "PersistenceError",
    "SkrySqlaError",
    "Filter",
    "And",
    "Or",
    "Not",
    "Equal",
    "In",
    "Like",
    "NotEqual",
    "GreaterThan",
    "LessThan",
    "GreaterOrEqual",
    "LessOrEqual",
    "Between",
    "IsNull",
    "IsNotNull",
    "ILike",
    "StartsWith",
    "EndsWith",
    "Contains",
    "NotIn",
    "JsonContains",
    "JsonHasKey",
    "ArrayContains",
    "ArrayOverlap",
    "apply_options",
    "TimestampableMixin",
    "TimestamableMixin",
    "UpdatedAtMixin",
    "UUIDIDMixin",
]
